apiVersion: v1
kind: Service
metadata:
  name: singularity-webapp-svc 
spec:
  selector:
    app: singularity-webapp 
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 5000 
  type: LoadBalancer
  clusterIP: 192.168.0.157
